name: crisp
description: Connect with Crisp Chat, register a user to chat (or not) and render a chat widget.
version: 0.1.8
homepage: https://github.com/lunahq/flutter-crisp

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.0
  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
