name: crisp
description: Connect with Crisp Chat, register a user to chat (or not) and render a chat widget.
version: 0.1.2
homepage: https://github.com/lunahq/flutter-crisp

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.5
  flutter_webview_plugin: ^0.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.oiluna.crisp
    pluginClass: CrispPlugin
